name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm ci
      - name: Release
        run: npm run semantic-release
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-windows:
    needs: release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch latest changes
        run: git pull origin master
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish Windows
        run: npm run publish:win
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPX_APPLICATION_ID: ${{ secrets.APPX_APPLICATION_ID }}
          APPX_DISPLAY_NAME: ${{ secrets.APPX_DISPLAY_NAME }}
          APPX_IDENTITY_NAME: ${{ secrets.APPX_IDENTITY_NAME }}
          APPX_PUBLISHER: ${{ secrets.APPX_PUBLISHER }}
          APPX_PUBLISHER_DISPLAY_NAME: ${{ secrets.APPX_PUBLISHER_DISPLAY_NAME }}
          CSC_IDENTITY_AUTO_DISCOVERY: true
